name: workfly

services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    develop:
      watch:
        - path: ./backend
          action: sync+restart
          target: /home/docker/code

  frontend:
    build:
      context: ./frontend
      target: dev
    command: npm run dev
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env.local
    develop:
      watch:
        - path: ./frontend
          action: sync
          target: /home/docker/code
